[project]
name = "clarinet-clarity-market"
requirements = ["nft-trait.clar", "nft-tradable-trait.clar"]
costs_version = 1
[contracts.appmap]
path = "contracts/appmap.clar"
depends_on = []

[contracts.nft-trait]
path = "contracts/nft-trait.clar"
depends_on = []

[contracts.nft-tradable-trait]
path = "contracts/nft-tradable-trait.clar"
depends_on = []

[contracts.loopbomb]
path = "contracts/loopbomb.clar"
depends_on = ["nft-trait", "nft-tradable-trait"]
