[project]
name = "clarinet-clarity-market"
requirements = ["nft-trait.clar", "operable.clar", "transferable.clar"]
costs_version = 1
[contracts.appmap]
path = "contracts/appmap.clar"
depends_on = []

[contracts.nft-trait]
path = "contracts/nft-trait.clar"
depends_on = []

[contracts.operable]
path = "contracts/operable.clar"
depends_on = []

[contracts.transferable]
path = "contracts/transferable.clar"
depends_on = []

[contracts.loopbomb]
path = "contracts/loopbomb.clar"
depends_on = ["nft-trait", "operable", "transferable"]
