[project]
name = "clarinet-clarity-market"
requirements = []
costs_version = 1

[contracts.crashpunks-v1]
path = "contracts/crashpunks-v1.clar"
depends_on = ["nft-trait", "operable", "transferable"]

[contracts.crashpunks-v2]
path = "contracts/crashpunks-v2.clar"
depends_on = ["nft-trait", "operable", "transferable"]

[contracts.commission-fixed]
path = "../../contracts/commission-fixed.clar"
depends_on = []

[contracts.commission-nop]
path = "../../contracts/commission-nop.clar"
depends_on = []

[contracts.commission-thisisnumberone]
path = "../../contracts/commission-thisisnumberone.clar"
depends_on = []

[contracts.commission-trait]
path = "../../contracts/traits/commission-trait.clar"
depends_on = []

[contracts.nft-trait]
path = "../../contracts/traits/nft-trait.clar"
depends_on = []

[contracts.operable]
path = "../../contracts/traits/operable.clar"
depends_on = []

[contracts.transferable]
path = "../../contracts/traits/transferable.clar"
depends_on = []
