
[project]
name = "loopbomb"
requirements = []
costs_version = 1

[contracts.loopbomb-genesis]
path = "contracts/loopbomb-genesis.clar"
depends_on = ["loopbomb-stx-v1", "nft-trait", "operable", "transferable"]

[contracts.loopbomb-stx-v1]
path = "contracts/loopbomb-stx-v1.clar"
depends_on = ["nft-trait", "operable", "transferable"]

[contracts.commission-fixed]
path = "../../contracts/commission-fixed.clar"
depends_on = []

[contracts.commission-nop]
path = "../../contracts/commission-nop.clar"
depends_on = []

[contracts.commission-loopbomb]
path = "../../contracts/commission-loopbomb.clar"
depends_on = []

[contracts.commission-trait]
path = "../../contracts/traits/commission-trait.clar"
depends_on = []

[contracts.nft-trait]
path = "../../contracts/traits/nft-trait.clar"
depends_on = []

[contracts.operable]
path = "../../contracts/traits/operable.clar"
depends_on = []

[contracts.transferable]
path = "../../contracts/traits/transferable.clar"
depends_on = []
